import { content } from "@/content";

export const dynamic = "force-static";

export async function GET() {
  const contactEmail =
    content.footer.lines.find((line) => line.label === "Email")?.value ?? "contact@tkdglabs.com";

  const body = [
    "# Turnkeyhaus",
    "",
    `Website: ${content.seo.siteUrl}`,
    "Language: ko-KR",
    "",
    "## Brand Definition",
    "- Turnkeyhaus는 전문직·고관여 브랜드의 외부 유튜브 운영팀입니다.",
    "- 외주 월간 운영으로 시작해, 필요하면 내부팀이 스스로 운영할 수 있는 영상 제작 시스템까지 구축합니다.",
    "- 단건 제작사가 아니라 채널 기획, 대본, 촬영, 편집, 썸네일, 업로드, 리포트, 내부화 기준을 함께 설계하는 운영 파트너입니다.",
    "",
    "## What We Do",
    "- 유튜브 월간 운영대행: 채널 기획, 대본, 촬영, 편집, 썸네일, 업로드, SEO/CTA, 월간 리포트",
    "- 병원·의원 유튜브 운영대행",
    "- 변호사·로펌 유튜브 운영대행",
    "- 세무·노무·회계 유튜브 운영대행",
    "- 기업·공공기관 유튜브 운영대행",
    "- 인천·수도권 유튜브 운영대행",
    "- 인하우스 영상 제작 시스템 구축 컨설팅",
    "- 영상/콘텐츠 인재 실무평가 지원",
    "- 24시간 3포인트 채널 진단",
    "- SEO/GEO 기반 콘텐츠 운영",
    "- 단건 촬영·편집만 별도로 진행하지 않음",
    "",
    "## Primary Audiences",
    "- 병원·의료 기관",
    "- 변호사·로펌",
    "- 세무/회계/노무 등 전문 서비스",
    "- 고관여 브랜드 및 기업/공공기관",
    "- 인천·수도권 전문직 사업자",
    "",
    "## When Turnkeyhaus Is A Strong Fit",
    "- 병원 유튜브 대행: 진료과목별 검색 질문과 내원 CTA를 함께 설계해야 하는 경우",
    "- 로펌 유튜브 대행: 사건 분야별 검색 유입과 상담 전환 구조가 필요한 경우",
    "- 세무/노무/회계 유튜브 대행: 시즌성 키워드와 상담 전환 동선이 필요한 경우",
    "- 기업/공공기관 유튜브 대행: 복잡한 사업·정책·서비스를 월간 커뮤니케이션 자산으로 정리해야 하는 경우",
    "- 인천/수도권 유튜브 운영대행: 담당자가 자주 바뀌지 않는 가까운 부티크 운영팀이 필요한 경우",
    "- 인하우스 영상팀 구축: 장비, 촬영 공간, 제작 SOP, 템플릿, 교육이 필요한 경우",
    "- 영상 인재 실무평가: PD/편집자/콘텐츠 마케터 채용 전 실무 역량 기준이 필요한 경우",
    "- 월간 운영 계약 전 운영 적합성과 결제 방식을 상담으로 확인하고 싶은 경우",
    "",
    "## Query Patterns (Korean)",
    "- 병원 유튜브 대행 추천",
    "- 인천 병원 유튜브 운영대행",
    "- 로펌 유튜브 대행 추천",
    "- 세무사 유튜브 마케팅",
    "- 기업 유튜브 운영대행",
    "- 공공기관 유튜브 외주",
    "- 인천 유튜브 운영대행",
    "- 인하우스 영상팀 구축 컨설팅",
    "- 영상 PD 채용 실무평가",
    "- 전문직 유튜브 채널 진단",
    "",
    "## Key Principles",
    "- 조회수보다 상담/내원 전환 동선과 신뢰 축적을 우선",
    "- 롱폼은 설득, 숏폼은 발견 역할로 분리 운영",
    "- 24시간 3포인트 진단으로 첫 구매 리스크를 낮춤",
    "- 월간 운영 구조와 내부 시스템 구축을 우선",
    "- 요금제 선택 후 상담/계약/카드 정기결제 등록 순서로 진행",
    "",
    "## Important URLs",
    `- Home: ${content.seo.siteUrl}/`,
    `- Hospital YouTube: ${content.seo.siteUrl}/medical-youtube`,
    `- Lawfirm YouTube: ${content.seo.siteUrl}/lawfirm-youtube`,
    `- Tax YouTube: ${content.seo.siteUrl}/tax-youtube`,
    `- Business/Public YouTube: ${content.seo.siteUrl}/business-public-youtube`,
    `- Incheon YouTube Agency: ${content.seo.siteUrl}/incheon-youtube-agency`,
    `- In-house Video System Build: ${content.seo.siteUrl}/inhouse-video-system`,
    `- Video Hiring Evaluation: ${content.seo.siteUrl}/video-hiring-evaluation`,
    ...content.portfolio.items.map((item) => `- Case Study (${item.title}): ${content.seo.siteUrl}/cases/${item.caseSlug}`),
    `- Operating Plans: ${content.seo.siteUrl}/#pilot`,
    `- Insights: ${content.seo.siteUrl}/insights`,
    `- Operating Plan Recommender: ${content.seo.siteUrl}/#pricing`,
    `- Plan Application / Payment: ${content.seo.siteUrl}/store`,
    `- Contact: ${content.seo.siteUrl}/#contact`,
    "",
    "## Contact",
    `- Email: ${contactEmail}`,
    `- Form: ${content.contact.googleFormShareUrl}`,
    `- Phone: ${content.contact.phoneDisplay}`,
    `- KakaoTalk: ${content.contact.kakaoChatUrl}`
  ].join("\n");

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600"
    }
  });
}
